language: ruby
rvm:
 — 2.5.3
before_script:
 — cp config/database.yml.travis config/database.yml
 — psql -c 'create database travis_ci_test' -U postgres
before_install:
 — gem install bundler -v 2.1.4
script:
 — bundle install --jobs=3 --retry=3 --deployment
 — bundle exec rails db:migrate RAILS_ENV=test
 # - bundle exec rails webpacker:install
 # - RAILS_ENV=test bundle exec rails webpacker:compile
 — bundle exec rspec
services:
 — postgresql
