language: ruby
rvm:
 — 2.5.3
before_script:
 — psql -c 'create database travis_ci_test;' -U postgres
before_install:
 — gem install bundler -v 2.1.4
script:
 — bundle exec rspec
services:
 — postgresql
